autoDetectedPackages:
- com.OmenKi.shortlink
enableAutoDetect: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
startOnDebug: false
